name: Build Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller pywin32

      - name: Compile with PyInstaller
        run: >
          pyinstaller --onefile --windowed --uac-admin 
          --icon=assets/app.ico 
          --add-data="assets;assets" 
          --name=SteamMussarelos 
          main.py

      - name: Sign EXE
        shell: powershell
        run: |
          $cert = New-SelfSignedCertificate -Type CodeSigning -Subject "CN=SteamMussarelos" -CertStoreLocation "Cert:\CurrentUser\My"
          try {
              Set-AuthenticodeSignature -FilePath "dist/SteamMussarelos.exe" -Certificate $cert -TimestampServer "http://digicert.com" -ErrorAction Stop
          } catch {
              Write-Warning "Falha no servidor de timestamp primario. Tentando assinar sem timestamp..."
              Set-AuthenticodeSignature -FilePath "dist/SteamMussarelos.exe" -Certificate $cert
          }


      - name: Verify Executable Location
        run: Get-ChildItem -Path dist -Filter *.exe

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/SteamMussarelos.exe
